import type { Metadata } from "next";
import { Marcellus,Montserrat } from "next/font/google";
import "./globals.css";



const marcellus = Marcellus({
  subsets:["latin"],
  weight:"400",
  variable:"--font-marcellus"
});

const montserrat = Montserrat({
  subsets:["latin"],
  weight:["100","200","300","400","500","600","700","800","900"],
  variable:"--font-montserrat"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      
      <body
        className={`${marcellus.variable} ${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
